/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'reusable-content': ReusableContent;
    faqs: Faq;
    orders: Order;
    products: Product;
    reviews: Review;
    discounts: Discount;
    stockItems: StockItem;
    suppliers: Supplier;
    brands: Brand;
    redirects: Redirect;
  };
  globals: {
    menus: Menu;
    globalSettings: GlobalSetting;
  };
}
export interface User {
  id: string;
  name: string;
  business?: string;
  roles?: ('admin' | 'customer' | 'user')[];
  stripeCustomerID?: string;
  skipSync?: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Media {
  id: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Page {
  id: string;
  fullTitle?: string;
  slug?: string;
  title: string;
  layout: (
    | {
        contentFields?: {
          layout?: 'oneColumn' | 'twoColumns' | 'threeColumns' | 'threeColumnsImage';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items?: {
            image?: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Product;
                      relationTo: 'products';
                    };
                url: string;
                label: string;
                image?: string | Media;
                description?: string;
                appearance?: 'primary' | 'secondary' | 'default';
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        ctaFields: {
          layout?: '2options' | 'simpleCentred' | 'centredImage';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items: {
            media?: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Product;
                      relationTo: 'products';
                    };
                url: string;
                label: string;
                image?: string | Media;
                description?: string;
                appearance?: 'primary' | 'secondary' | 'default';
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        featuredFaqsFields: {
          layout?: 'threeColumn' | 'centredAccordion';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'faqs';
              }[]
            | {
                value: Faq;
                relationTo: 'faqs';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredFaqs';
      }
    | {
        featuredLogosFields?: {
          layout?: 'threeColumn' | 'centredAccordion';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          images?: {
            image: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredLogos';
      }
    | {
        featuredProductsFields: {
          layout?: 'single' | 'threeColumn' | 'threeFancy';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'products';
              }[]
            | {
                value: Product;
                relationTo: 'products';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredProducts';
      }
    | {
        featuredReviewsFields: {
          layout?: 'single' | 'threeColumns';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'reviews';
              }[]
            | {
                value: Review;
                relationTo: 'reviews';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredReviews';
      }
    | {
        heroFields: {
          image: string | Media;
          textColor?: 'white' | 'offwhite' | 'black' | 'green' | 'lightgreen' | 'khaki' | 'lightbrown' | 'lighterbrown';
          content?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Product;
                    relationTo: 'products';
                  };
              url: string;
              label: string;
              image?: string | Media;
              description?: string;
              appearance?: 'default' | 'primary' | 'secondary';
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'hero';
      }
    | {
        mediaContentFields: {
          layout?: 'contentMedia' | 'mediaContent' | 'centredMedia';
          media: string | Media;
          content?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Product;
                    relationTo: 'products';
                  };
              url: string;
              label: string;
              image?: string | Media;
              description?: string;
              appearance?: 'primary' | 'secondary' | 'default';
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        reusableContentBlockFields: {
          reusableContent: string | ReusableContent;
        };
        id?: string;
        blockName?: string;
        blockType: 'reusableContentBlock';
      }
  )[];
  parent?: string | Page;
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Product {
  id: string;
  fullTitle?: string;
  slug?: string;
  title: string;
  description: string;
  stripeID?: string;
  quantity: number;
  stock?: {
    stock?: string[] | StockItem[];
    id?: string;
  }[];
  currency?: string;
  unit_amount?: number;
  layout: (
    | {
        contentFields?: {
          layout?: 'oneColumn' | 'twoColumns' | 'threeColumns' | 'threeColumnsImage';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items?: {
            image?: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Product;
                      relationTo: 'products';
                    };
                url: string;
                label: string;
                image?: string | Media;
                description?: string;
                appearance?: 'primary' | 'secondary' | 'default';
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        ctaFields: {
          layout?: '2options' | 'simpleCentred' | 'centredImage';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items: {
            media?: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Product;
                      relationTo: 'products';
                    };
                url: string;
                label: string;
                image?: string | Media;
                description?: string;
                appearance?: 'primary' | 'secondary' | 'default';
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        featuredFaqsFields: {
          layout?: 'threeColumn' | 'centredAccordion';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'faqs';
              }[]
            | {
                value: Faq;
                relationTo: 'faqs';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredFaqs';
      }
    | {
        featuredLogosFields?: {
          layout?: 'threeColumn' | 'centredAccordion';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          images?: {
            image: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredLogos';
      }
    | {
        featuredReviewsFields: {
          layout?: 'single' | 'threeColumns';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'reviews';
              }[]
            | {
                value: Review;
                relationTo: 'reviews';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredReviews';
      }
    | {
        heroFields: {
          image: string | Media;
          textColor?: 'white' | 'offwhite' | 'black' | 'green' | 'lightgreen' | 'khaki' | 'lightbrown' | 'lighterbrown';
          content?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Product;
                    relationTo: 'products';
                  };
              url: string;
              label: string;
              image?: string | Media;
              description?: string;
              appearance?: 'default' | 'primary' | 'secondary';
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'hero';
      }
    | {
        mediaContentFields: {
          layout?: 'contentMedia' | 'mediaContent' | 'centredMedia';
          media: string | Media;
          content?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Product;
                    relationTo: 'products';
                  };
              url: string;
              label: string;
              image?: string | Media;
              description?: string;
              appearance?: 'primary' | 'secondary' | 'default';
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        perksFields?: {
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          items?: {
            image: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'perks';
      }
    | {
        productComponentsFields: {
          layout: 'twoColumns' | 'fourColumns' | 'imageLeft' | 'imageRight';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          features?: {
            image: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
          image: string | Media;
          content?: {
            content?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'productComponents';
      }
    | {
        productOverviewFields?: {
          images?: {
            image: string | Media;
            id?: string;
          }[];
          content?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'productOverview';
      }
    | {
        reusableContentBlockFields: {
          reusableContent: string | ReusableContent;
        };
        id?: string;
        blockName?: string;
        blockType: 'reusableContentBlock';
      }
  )[];
  parent?: string | Product;
  breadcrumbs?: {
    doc?: string | Product;
    url?: string;
    label?: string;
    id?: string;
  }[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface StockItem {
  id: string;
  title?: string;
  type?: 'card' | 'gift' | 'box' | 'ribbon';
  description?: string;
  value?: 'high' | 'medium' | 'low' | 'discontinued';
  brand?: string | Brand;
  supplier?: string | Supplier;
  sku?: string;
  totalQty?: number;
  retailUnitCost?: number;
  wholesaleUnitCost?: number;
  comments?: string;
  discontinued?: boolean;
  image?: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface Brand {
  id: string;
  title: string;
  website: string;
  comments?: string;
  logo: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface Supplier {
  id: string;
  title: string;
  website: string;
  relationship: 'positive' | 'neutral' | 'negative';
  comments?: string;
  logo: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface Faq {
  id: string;
  question?: string;
  answer?: {
    [k: string]: unknown;
  }[];
  tags?: {
    name?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Review {
  id: string;
  note?: string;
  providerName?: string;
  providerOrg?: string;
  link?: string;
  channel?: 'instagram' | 'facebook' | 'other';
  image?: string | Media;
  rating?: number;
  updatedAt: string;
  createdAt: string;
}
export interface ReusableContent {
  id: string;
  title: string;
  layout: (
    | {
        contentFields?: {
          layout?: 'oneColumn' | 'twoColumns' | 'threeColumns' | 'threeColumnsImage';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items?: {
            image?: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Product;
                      relationTo: 'products';
                    };
                url: string;
                label: string;
                image?: string | Media;
                description?: string;
                appearance?: 'primary' | 'secondary' | 'default';
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        ctaFields: {
          layout?: '2options' | 'simpleCentred' | 'centredImage';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items: {
            media?: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Product;
                      relationTo: 'products';
                    };
                url: string;
                label: string;
                image?: string | Media;
                description?: string;
                appearance?: 'primary' | 'secondary' | 'default';
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        featuredFaqsFields: {
          layout?: 'threeColumn' | 'centredAccordion';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'faqs';
              }[]
            | {
                value: Faq;
                relationTo: 'faqs';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredFaqs';
      }
    | {
        featuredLogosFields?: {
          layout?: 'threeColumn' | 'centredAccordion';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          images?: {
            image: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredLogos';
      }
    | {
        featuredProductsFields: {
          layout?: 'single' | 'threeColumn' | 'threeFancy';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'products';
              }[]
            | {
                value: Product;
                relationTo: 'products';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredProducts';
      }
    | {
        featuredReviewsFields: {
          layout?: 'single' | 'threeColumns';
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          leadingContent?: {
            [k: string]: unknown;
          }[];
          trailingContent?: {
            [k: string]: unknown;
          }[];
          items:
            | {
                value: string;
                relationTo: 'reviews';
              }[]
            | {
                value: Review;
                relationTo: 'reviews';
              }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'featuredReviews';
      }
    | {
        heroFields: {
          image: string | Media;
          textColor?: 'white' | 'offwhite' | 'black' | 'green' | 'lightgreen' | 'khaki' | 'lightbrown' | 'lighterbrown';
          content?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Product;
                    relationTo: 'products';
                  };
              url: string;
              label: string;
              image?: string | Media;
              description?: string;
              appearance?: 'default' | 'primary' | 'secondary';
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'hero';
      }
    | {
        mediaContentFields: {
          layout?: 'contentMedia' | 'mediaContent' | 'centredMedia';
          media: string | Media;
          content?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Product;
                    relationTo: 'products';
                  };
              url: string;
              label: string;
              image?: string | Media;
              description?: string;
              appearance?: 'primary' | 'secondary' | 'default';
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'mediaContent';
      }
    | {
        perksFields?: {
          bgColor?:
            | 'text-white'
            | 'text-offwhite'
            | 'text-black'
            | 'text-green'
            | 'text-lightgreen'
            | 'text-khaki'
            | 'text-lightbrown'
            | 'text-lighterbrown';
          items?: {
            image: string | Media;
            content?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'perks';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
export interface Order {
  id: string;
  fullTitle?: string;
  customer?: string | User;
  status?: 'pending' | 'cancelled' | 'onhold' | 'processing' | 'completed';
  termsAccepted?: boolean;
  subtotalAmount: string;
  shippingAmount: string;
  discountAmount: string;
  invoiceAmount: string;
  orderID: string;
  notes?: string;
  stripeInvoiceID?: string;
  stripePaymentIntentID?: string;
  events?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  items: {
    type?: 'product' | 'discount' | 'other';
    thankly?: {
      status?: 'Processing' | 'Shipped' | 'Delivered' | 'Cancelled';
      product?: string[] | Product[];
      tracking?: {
        number?: string;
        link?: string;
      };
      stripePriceID?: string;
      message?: {
        styles?: 'normal' | 'cursive' | 'capitals';
        text?: string;
      };
      receiver?: {
        name?: string;
        business?: string;
        type?: 'Residential' | 'Business' | 'PO Box / Locker';
        fulladdress?: string;
        addressLine1?: string;
        addressLine2?: string;
        suburb?: string;
        state?: string;
        postcode?: string;
      };
      requestedShipDate?: string;
    };
    discount?: string | Discount;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Discount {
  id: string;
  code?: string;
  description?: string;
  activeDate?: string;
  expiryDate?: string;
  value?: number;
  type?: 'percent' | 'amount';
  updatedAt: string;
  createdAt: string;
}
export interface Redirect {
  id: string;
  from: string;
  to: {
    type?: 'reference' | 'custom';
    reference:
      | {
          value: string | Page;
          relationTo: 'pages';
        }
      | {
          value: string | Product;
          relationTo: 'products';
        };
    url: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Menu {
  id: string;
  header: {
    name: string;
    banner?: string;
    menuItems?: {
      useSubMenu?: boolean;
      name?: string;
      links?: {
        link: {
          type?: 'reference' | 'custom';
          newTab?: boolean;
          reference:
            | {
                value: string | Page;
                relationTo: 'pages';
              }
            | {
                value: string | Product;
                relationTo: 'products';
              };
          url: string;
          label: string;
          image?: string | Media;
          description?: string;
          appearance?: 'default' | 'primary' | 'secondary';
        };
        id?: string;
      }[];
      id?: string;
    }[];
  };
  footer: {
    logo?: string | Media;
    name: string;
    tagline: string;
    copyright: string;
    columns?: {
      name: string;
      links?: {
        link: {
          type?: 'reference' | 'custom';
          newTab?: boolean;
          reference:
            | {
                value: string | Page;
                relationTo: 'pages';
              }
            | {
                value: string | Product;
                relationTo: 'products';
              };
          url: string;
          label: string;
          image?: string | Media;
          description?: string;
          appearance?: 'default' | 'primary' | 'secondary';
        };
        id?: string;
      }[];
      id?: string;
    }[];
  };
  updatedAt?: string;
  createdAt?: string;
}
export interface GlobalSetting {
  id: string;
  banner?: string;
  updatedAt?: string;
  createdAt?: string;
}
